# Generated by Django 4.2.6 on 2023-10-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='fullname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='regno',
            field=models.CharField(default='', max_length=100),
        ),
    ]
