# Generated by Django 4.2.6 on 2023-10-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees_app', '0002_feepayment_fullname_feepayment_regno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepayment',
            name='payment_date',
            field=models.CharField(max_length=100),
        ),
    ]
