# Generated by Django 4.2.6 on 2023-10-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees_app', '0003_alter_feepayment_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepayment',
            name='payment_date',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
