# Generated by Django 4.2.6 on 2023-11-03 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
        ('fees_app', '0004_alter_feepayment_payment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feepayment',
            name='regno',
        ),
        migrations.AddField(
            model_name='feepayment',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school_app.student'),
        ),
    ]
