# Generated by Django 4.2.6 on 2023-11-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees_app', '0005_remove_feepayment_regno_feepayment_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='regno',
            field=models.CharField(default='', max_length=100),
        ),
    ]
