# Generated by Django 4.2.6 on 2024-01-29 08:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fees_app', '0006_feepayment_regno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feepayment',
            name='date_reg',
        ),
        migrations.RemoveField(
            model_name='feepayment',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='feepayment',
            name='regno',
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='payment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
