# Generated by Django 4.2.6 on 2023-10-07 07:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(max_length=100)),
                ('fullname', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('contact', models.CharField(default=1, max_length=100)),
                ('date_reg', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
