# Generated by Django 4.2.6 on 2024-02-03 08:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.IntegerField()),
                ('fullname', models.CharField(max_length=100)),
                ('classs', models.CharField(default=1, max_length=100)),
                ('parents_name', models.CharField(default='', max_length=100)),
                ('parents_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('fees', models.CharField(max_length=100)),
                ('date_reg', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
