# Generated by Django 4.2.6 on 2024-01-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='course',
            new_name='fees',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='contact',
            new_name='parents_contact',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.AddField(
            model_name='student',
            name='parents_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
