# Generated by Django 4.2.6 on 2024-01-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0002_rename_course_student_fees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parents_contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
