# Generated by Django 4.2.6 on 2024-01-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0003_alter_student_parents_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='classs',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
