# Generated by Django 4.2.6 on 2024-01-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0004_student_classs'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='fees',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
