# Generated by Django 4.2.6 on 2024-01-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0005_student_balance_alter_student_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='fees',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
