# Generated by Django 4.2.6 on 2024-01-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0006_alter_student_balance_alter_student_fees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='balance',
        ),
        migrations.AlterField(
            model_name='student',
            name='fees',
            field=models.CharField(max_length=100),
        ),
    ]
