# Generated by Django 4.2.6 on 2024-01-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0007_remove_student_balance_alter_student_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='regno',
            field=models.IntegerField(),
        ),
    ]
